exclude: '.patch$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs

  # - repo: https://github.com/elektrobit-contrib/eclipse-score_devcontainer
  #   rev: c2a743cb05d841eb2236daba55c3458c0a217197
  #   hooks:
  #     - id: reuse-annotate
