# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Bazel Build & Test module
# This workflow runs Bazel build and test when triggered by specific pull request events.

name: Bazel Build & Test module (with host toolchain)
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  build_and_test_host:
    # Starting with Ubuntu 24.04 apparmor breaks Bazels linux-sandbox: https://github.com/bazelbuild/bazel/issues/24081
    runs-on: ubuntu-22.04
    steps:
      - run: df -h
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          repository-cache: true
      - uses: actions/checkout@v6
      - name: Bazel build targets
        run: |
          bazel build //...
      - name: Bazel test targets
        run: |
          bazel test //... --build_tests_only
